Task 4 employees table
Alenapadsekina/js_study pull request #8
Opened 2018-05-16 08:31 UTC by Alenapadsekina

2018-05-17 10:44 UTC, SergeBondar commented on Website/index.html
> +    <span class="teams">
Для вложенных структур обычно используют div

2018-05-17 10:44 UTC, SergeBondar commented on Website/index.html
> +				<option value="" class="dropdown"> </option>
class лучше повесить на select

2018-05-17 10:44 UTC, SergeBondar commented on Website/index.html
> +		<input  class="button" type="button" value="Generate report" onclick="testButton(); employeesAvailability.js">
employeesAvailability.js - а вот это зачем тут?

2018-05-31 11:16 UTC, SergeBondar reviewed
и что-то с отступами в html файле

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +            if (employees[i].team == team) {
строгое

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +    function defineTeamMembers(team) { // populate 'group' array with corresponding team members
у тебя получилась очень сложная структура - часть функций объявлена глобально, часть внутри других функций
нужно унифицировать объявление функций

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +            function populateTeamMembers() { // create lines in 'Members' dropdown and popoulate them with group members
populate

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +                    var select = document.getElementById("teamMembers");
это лучше объявить до цикла

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +    var table = document.getElementById("reportTable");
это лучше сделать перед циклом, и тогда тебе не нужно будет каждый раз объявлять table
и еще - если ты сначала создашь строку, добавишь к ней всю инфу, и только потом добавишь ее в таблицу - dom обновится только один раз, а так - как у тебя - при каждой операции

2018-05-31 11:16 UTC, SergeBondar commented on Website/employeesAvailability.js
> +function validation(errorMessage) { // create error message
showError?

2018-05-31 11:16 UTC, SergeBondar commented on Website/index.html
> +					<option value="Main releases" class="dropdown" onclick="selectTeam()">Main releases</option>
onclick вешается на весь select один раз

2018-06-12 07:16 UTC, Alenapadsekina commented on Website/employeesAvailability.js
> +function validation(errorMessage) { // create error message
исправила

2018-06-12 07:18 UTC, Alenapadsekina commented on Website/employeesAvailability.js
> +                    var select = document.getElementById("teamMembers");
исправила

2018-06-12 07:18 UTC, Alenapadsekina commented on Website/employeesAvailability.js
> +            function populateTeamMembers() { // create lines in 'Members' dropdown and popoulate them with group members
исправила

2018-06-12 07:19 UTC, Alenapadsekina commented on Website/employeesAvailability.js
> +            if (employees[i].team == team) {
исправила

2018-06-12 07:40 UTC, Alenapadsekina commented on Website/index.html
> +					<option value="Main releases" class="dropdown" onclick="selectTeam()">Main releases</option>
исправила

2018-06-13 19:31 UTC, SergeBondar commented on Website/employeesAvailability.js
> +        function populateDropdown() {
Не совсем понимаю, зачем тебе эти 3 функции populateDropdown (странное название, ни о чем не говорит, cleanDropdown (обычно используется слово clear, но для 4 строчек редко создается отдельная функция) и populateTeamMembers
Почему бы просто не создать одну функцию - populateTeamMembers, и в ней реализовать всю вот эту логику?

2018-06-13 19:31 UTC, SergeBondar commented on Website/employeesAvailability.js
> +    function defineTeamMembers(team) { // populate 'group' array with corresponding team members
define, а в комментарии- populate?
давай еще раз это обсудим

2018-06-13 19:31 UTC, SergeBondar commented on Website/employeesAvailability.js
> +            errorMessage = "Please define a team";
а почему нельзя сразу строку передать в функцию?
зачем нам эта переменная?

2018-06-13 19:31 UTC, SergeBondar commented on Website/index.html
> +    			<select id="teams" class="dropdown" onclick="selectTeam()">
извини, для select тогда будет использоваться onchange событие

2018-06-14 12:50 UTC, SergeBondar approved these changes

2018-06-18 13:57 UTC, MaxMarasanov commented
По условию, если член команды не выбран, то должна выводиться вся таблица, иначе - только для выбранного члена.

Сейчас же не выбрать члена команды нельзя в принципе (по умолчанию уже кто-то выбран), а при любом выборе строит таблицу для всей команды.

2018-06-18 13:57 UTC, MaxMarasanov requested changes
Нужно подправить генерацию таблицы

2018-06-29 13:34 UTC, MaxMarasanov approved these changes

2018-06-29 14:26 UTC, merged